const Constants = {
  USER_SIGNED_IN: 'USER_SIGNED_IN',
  CURRENT_USER: 'CURRENT_USER',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
  SESSION_ERROR: 'SESSION_ERROR',
  REGISTRATION_ERROR: 'REGISTRATION_ERROR',

export default Constants;
